line_length: 
  - 400 # warning
  - 500 # error

disabled_rules:
  - trailing_whitespace


excluded:
        - Pods


function_parameter_count:
        - warning: 6
        - error: 8



opt_in_rules:
  - closure_end_indentation

function_body_length:
        - 100 #warning
        - 200 #error

